name: CI
# https://medium.com/@michaelekpang/creating-a-ci-cd-pipeline-using-github-actions-b65bb248edfe
on: 
  push:
    branches:    
      - master
      # 
  pull_request:
    branches:
      - master

jobs:
  build: # Job name

    runs-on: ubuntu-latest # which operating system will githbut do this job

    strategy:
      matrix:
        node-version: [12.x]
    steps: # multiple steps we need for this "build" job
      - uses: actions/checkout@v1 # github will use checkout@v1 api of version one
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn install
        run: |
          yarn install
      # - name: yarn test1
      #   run: |
      #     yarn test1 --if-present
      #   env:
      #     CI: true
          
      # - name: yarn build
      #   run: |
      #     yarn run build --if-present
      - name: Add remote origin
        run: |
          git remote add stage https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
      - name: Deploy to Heroku
        run: |
          git push stage HEAD:master -f